name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /www/wwwroot/afif.projectskripsi.live && rm -rf * && git clone https://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@github.com/abunaum/telur.git && cd telur && composer install && php spark command:name DB && php spark migrate -all && php db:seed Persiapan
